'use strict';

angular.module('vimeoApp')
  .factory('userService', ['authenticationService', 'vimeoApiService', 'videoService', '$q',
    function (authenticationService, vimeoApiService, videoService, $q) {

      var token = 'ee100b46d32c27be3b879e277ffecaa8';//OAuth token generated by vimeo

      var vimeoUser = null;

      var api = {
        getVimeoUser: function () {
          return vimeoUser ? $q.when(vimeoUser) : api.login();
        },
        login: function () {
          return authenticationService.authenticate(token).then(function (data) {
            return vimeoApiService.findUserInfo().then(function (user) {
              vimeoUser = user;
              return vimeoUser;
            })
          });
        },
        getUserVideos: function () {
          return videoService.getVideos();
        }
      };
      return api;

    }]);

